version: '3.9'

services:
  mongodb:
    image: mongo:latest
    container_name: UTD
    ports:
      - "27017:27017"
    restart: always
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: 